apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arena
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - redis.yaml
  - gateway.yaml
  - matchmaker.yaml
  - gameserver.yaml
  - ingress.yaml
  - networkpolicy.yaml
