apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
  namespace: arena
spec:
  tls:
    - hosts: [arena.example.com]
      secretName: arena-gateway-tls
  rules:
    - host: arena.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8080
